artifact_location: file:///d:/Workspace/Classes/TuDuyTinhToan/cleaning-service-recommendation/runs/mlflow/784353608099443613
creation_time: 1750324737041
experiment_id: '784353608099443613'
last_update_time: 1750324737041
lifecycle_stage: active
name: /Shared/Ultralytics
