artifact_location: file:///d:/Workspace/Classes/TuDuyTinhToan/cleaning-service-recommendation/runs/mlflow/0
creation_time: 1750324736996
experiment_id: '0'
last_update_time: 1750324736996
lifecycle_stage: active
name: Default
